#!/bin/bash
cal(){ echo "scale=2;($1*4.3 + $2*4.0 + $3*3.0 + $4*2.0)/($1+$2+$3+$4+$5)"|bc;}

zzz(){ z=`echo $@|tr " " "+"|bc`
       if [ $z -eq 0 ];then
        echo "うーん、乳飲み子かな？ｗ";exit
       fi
}

err(){ if ! `echo ${r[@]}|grep -q "$1"`;then
        echo 'うーん、不正な値！ｗ';exit
       fi
}

grade=(S A B C D)
r=(`for((i=0;i<400;i++));do echo $i*0.5|bc;done|xargs`)
score=""

if [ -z "$*" ];then
 for i in ${grade[@]};do 
  echo ${i}\?:
  read input
  err $input
  score="$score $input"
 done
 zzz $score
 cal $score
elif [ $# == 5 ];then
 for i in "$@";do
  err $i
 done
 zzz $@
 cal $@
else
 echo 'うーん、不正な引数！ｗ'
fi
